# 数据操作
在深度学习中，张量（Tensor）代表的是 N 维数组，以下是基于 Pytorch 对 Tensor 所做的一些基本操作。

## 1. 基本操作
首先需要引入 torch：

In [1]:
import torch

可以利用 arange 创建一个行向量 x：

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过 shape 访问 Tensor 的形状：

In [3]:
x.shape

torch.Size([12])

获取 Tensor 中元素的总数：

In [35]:
x.numel()

12

改变 Tensor 的 shape 可以使用 reshape 方法：

In [36]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

在改变 shape 的时候，我们只需要知道 (height, width) 中的某一个维度的大小之后，另一维度的大小可以被自动地计算出来，例如：

In [37]:
X1 = x.reshape(-1, 4)
X1

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

效果和 x.shape(3, 4) 的效果是一模一样的。

创建全 0、1、其他常量的 Tensor 方式如下：

In [38]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [39]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

从某个特定的概率分布中随机采样得到 Tensor 中每个元素的值，下面例子构造了 (3, 4) 的 Tensor，元素的值是从均值为 0，标准差为 1 的标准高斯分布（正态分布）中随机采样：

In [40]:
torch.randn(3, 4)

tensor([[-2.4934, -0.8067, -0.6362,  0.6782],
        [ 0.7279,  1.9870, -0.7604,  0.7493],
        [-1.4734,  0.5676, -1.1481, -0.6415]])

从 Python 列表中为 Tensor 赋予特定的值：

In [41]:
torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

## 2. 运算符

In [42]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素求幂：

In [43]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

将多个 Tensor 拼接在一起形成一个更大的 Tensor：

In [44]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.concat((X, Y), dim=0), torch.concat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符构建二元 Tensor：

In [45]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

求和：

In [46]:
X.sum()

tensor(66.)

## 3. 广播机制
在某些情况下，两个 Tensor 的 shape 不相同，如果想让这两个 shape 按照元素进行操作，就需要用到广播机制（broadcasting mechamism）。如下例子：

In [48]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

由于 a 和 b 的 shape 不匹配，我们将 a 和 b 广播为更大的矩阵，如下所示（a 复制列，b 复制行）：

In [49]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 4. 索引和切片
索引读取，和 Python 逻辑一致：

In [50]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

通过索引写入元素：

In [52]:
X[1:2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 9.,  9.,  9.,  9.],
        [ 8.,  9., 10., 11.]])

## 5. 练习
#### 5.1 运行本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。

In [53]:
X < Y, X > Y

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

#### 5.2 用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？

In [63]:
c = torch.arange(3).reshape(3, 1, 1)
d = torch.arange(2).reshape(1, 1, 2)
c, d

(tensor([[[0]],
 
         [[1]],
 
         [[2]]]),
 tensor([[[0, 1]]]))

In [64]:
c + d

tensor([[[0, 1]],

        [[1, 2]],

        [[2, 3]]])